// <auto-generated />
using System;
using EkDers.Data.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace EkDers.Data.Migrations
{
    [DbContext(typeof(EkdersDbContext))]
    partial class EkdersDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("EkDers.Entity.DbEntity.Brans", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("BransAdi")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime>("CreateDate")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.HasKey("Id");

                    b.ToTable("Brans", (string)null);
                });

            modelBuilder.Entity("EkDers.Entity.DbEntity.Donem", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreateDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("DonemAdi")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("DonemAy")
                        .HasColumnType("int");

                    b.Property<DateOnly>("DonemBaslangicTarihi")
                        .HasColumnType("date");

                    b.Property<DateOnly>("DonemBitisTarihi")
                        .HasColumnType("date");

                    b.Property<int>("DonemYil")
                        .HasColumnType("int");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.HasKey("Id");

                    b.ToTable("Donem", (string)null);
                });

            modelBuilder.Entity("EkDers.Entity.DbEntity.EkdersKodu", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Aciklama")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<DateTime>("CreateDate")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<string>("KodAd")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Kodu")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.ToTable("EkdersKodu", (string)null);
                });

            modelBuilder.Entity("EkDers.Entity.DbEntity.EkdersResult", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreateDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Data")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("DonemId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("Gun0")
                        .HasColumnType("int");

                    b.Property<int>("Gun1")
                        .HasColumnType("int");

                    b.Property<int>("Gun10")
                        .HasColumnType("int");

                    b.Property<int>("Gun11")
                        .HasColumnType("int");

                    b.Property<int>("Gun13")
                        .HasColumnType("int");

                    b.Property<int>("Gun14")
                        .HasColumnType("int");

                    b.Property<int>("Gun15")
                        .HasColumnType("int");

                    b.Property<int>("Gun16")
                        .HasColumnType("int");

                    b.Property<int>("Gun17")
                        .HasColumnType("int");

                    b.Property<int>("Gun18")
                        .HasColumnType("int");

                    b.Property<int>("Gun19")
                        .HasColumnType("int");

                    b.Property<int>("Gun2")
                        .HasColumnType("int");

                    b.Property<int>("Gun20")
                        .HasColumnType("int");

                    b.Property<int>("Gun21")
                        .HasColumnType("int");

                    b.Property<int>("Gun22")
                        .HasColumnType("int");

                    b.Property<int>("Gun23")
                        .HasColumnType("int");

                    b.Property<int>("Gun24")
                        .HasColumnType("int");

                    b.Property<int>("Gun25")
                        .HasColumnType("int");

                    b.Property<int>("Gun26")
                        .HasColumnType("int");

                    b.Property<int>("Gun27")
                        .HasColumnType("int");

                    b.Property<int>("Gun28")
                        .HasColumnType("int");

                    b.Property<int>("Gun29")
                        .HasColumnType("int");

                    b.Property<int>("Gun3")
                        .HasColumnType("int");

                    b.Property<int>("Gun30")
                        .HasColumnType("int");

                    b.Property<int>("Gun4")
                        .HasColumnType("int");

                    b.Property<int>("Gun5")
                        .HasColumnType("int");

                    b.Property<int>("Gun6")
                        .HasColumnType("int");

                    b.Property<int>("Gun7")
                        .HasColumnType("int");

                    b.Property<int>("Gun8")
                        .HasColumnType("int");

                    b.Property<int>("Gun9")
                        .HasColumnType("int");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<Guid?>("IzinId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("KodId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("PersonelId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("DonemId");

                    b.HasIndex("IzinId");

                    b.HasIndex("KodId");

                    b.HasIndex("PersonelId");

                    b.ToTable("EkdersResult", (string)null);
                });

            modelBuilder.Entity("EkDers.Entity.DbEntity.Gorev", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreateDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("GorevAd")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.HasKey("Id");

                    b.ToTable("Gorev", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("0c30e774-4b13-4ec4-b354-157728ffb11c"),
                            CreateDate = new DateTime(2024, 9, 19, 16, 33, 30, 61, DateTimeKind.Local).AddTicks(7884),
                            GorevAd = "Müdür",
                            IsDeleted = false
                        },
                        new
                        {
                            Id = new Guid("3b4dcbef-c723-40be-b73e-19cd09604c59"),
                            CreateDate = new DateTime(2024, 9, 19, 16, 33, 30, 61, DateTimeKind.Local).AddTicks(7906),
                            GorevAd = "Müdür Yardımcısı",
                            IsDeleted = false
                        },
                        new
                        {
                            Id = new Guid("35084397-55c0-47bb-b1fe-17f02ff27601"),
                            CreateDate = new DateTime(2024, 9, 19, 16, 33, 30, 61, DateTimeKind.Local).AddTicks(7908),
                            GorevAd = "Öğretmen",
                            IsDeleted = false
                        },
                        new
                        {
                            Id = new Guid("9b12ff59-0858-4fa2-9c20-f1ecd1c60098"),
                            CreateDate = new DateTime(2024, 9, 19, 16, 33, 30, 61, DateTimeKind.Local).AddTicks(7909),
                            GorevAd = "Uzman Öğretmen",
                            IsDeleted = false
                        },
                        new
                        {
                            Id = new Guid("ac86700e-3f47-4b67-b0cd-06c038065ca7"),
                            CreateDate = new DateTime(2024, 9, 19, 16, 33, 30, 61, DateTimeKind.Local).AddTicks(7910),
                            GorevAd = "Baş Öğretmen",
                            IsDeleted = false
                        });
                });

            modelBuilder.Entity("EkDers.Entity.DbEntity.Izin", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Aciklama")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<DateOnly>("BaslagicTarihi")
                        .HasColumnType("date");

                    b.Property<DateTime>("CreateDate")
                        .HasColumnType("datetime2");

                    b.Property<bool>("EkDerskesilecekmi")
                        .HasColumnType("bit");

                    b.Property<int>("GunSayisi")
                        .HasColumnType("int");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<Guid>("IzinTuruId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("PersonelId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("IzinTuruId");

                    b.HasIndex("PersonelId");

                    b.ToTable("Izin", (string)null);
                });

            modelBuilder.Entity("EkDers.Entity.DbEntity.IzinTuru", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreateDate")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<string>("TurAdi")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.HasKey("Id");

                    b.ToTable("IzinTuru", (string)null);
                });

            modelBuilder.Entity("EkDers.Entity.DbEntity.KurumBilgi", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreateDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Deger")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("Etiket")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.HasKey("Id");

                    b.ToTable("KurumBilgi", (string)null);
                });

            modelBuilder.Entity("EkDers.Entity.DbEntity.Personel", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Ad")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<Guid>("BransId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreateDate")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("GorevId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<string>("Soyad")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("TCKN")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Telefon")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.HasKey("Id");

                    b.HasIndex("BransId");

                    b.HasIndex("GorevId");

                    b.ToTable("Personel", (string)null);
                });

            modelBuilder.Entity("EkDers.Entity.DbEntity.Tatil", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateOnly>("BaslangicTarihi")
                        .HasColumnType("date");

                    b.Property<DateTime>("CreateDate")
                        .HasColumnType("datetime2");

                    b.Property<bool>("EkDersKesilirmi")
                        .HasColumnType("bit");

                    b.Property<int>("GunSayisi")
                        .HasColumnType("int");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<string>("TatilAd")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("TatilTuru")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("Yarimgunvarmi")
                        .HasColumnType("bit");

                    b.HasKey("Id");

                    b.ToTable("Tatil", (string)null);
                });

            modelBuilder.Entity("EkDers.Entity.DbEntity.EkdersResult", b =>
                {
                    b.HasOne("EkDers.Entity.DbEntity.Donem", "Donem")
                        .WithMany("EkdersResults")
                        .HasForeignKey("DonemId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("EkDers.Entity.DbEntity.Izin", null)
                        .WithMany("EkDersResults")
                        .HasForeignKey("IzinId");

                    b.HasOne("EkDers.Entity.DbEntity.EkdersKodu", "Kod")
                        .WithMany("EkdersResults")
                        .HasForeignKey("KodId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("EkDers.Entity.DbEntity.Personel", "Personel")
                        .WithMany()
                        .HasForeignKey("PersonelId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Donem");

                    b.Navigation("Kod");

                    b.Navigation("Personel");
                });

            modelBuilder.Entity("EkDers.Entity.DbEntity.Izin", b =>
                {
                    b.HasOne("EkDers.Entity.DbEntity.IzinTuru", "IzinTuru")
                        .WithMany("Izins")
                        .HasForeignKey("IzinTuruId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("EkDers.Entity.DbEntity.Personel", "Personel")
                        .WithMany()
                        .HasForeignKey("PersonelId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("IzinTuru");

                    b.Navigation("Personel");
                });

            modelBuilder.Entity("EkDers.Entity.DbEntity.Personel", b =>
                {
                    b.HasOne("EkDers.Entity.DbEntity.Brans", "Brans")
                        .WithMany("Personels")
                        .HasForeignKey("BransId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("EkDers.Entity.DbEntity.Gorev", "Gorev")
                        .WithMany("Personels")
                        .HasForeignKey("GorevId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Brans");

                    b.Navigation("Gorev");
                });

            modelBuilder.Entity("EkDers.Entity.DbEntity.Brans", b =>
                {
                    b.Navigation("Personels");
                });

            modelBuilder.Entity("EkDers.Entity.DbEntity.Donem", b =>
                {
                    b.Navigation("EkdersResults");
                });

            modelBuilder.Entity("EkDers.Entity.DbEntity.EkdersKodu", b =>
                {
                    b.Navigation("EkdersResults");
                });

            modelBuilder.Entity("EkDers.Entity.DbEntity.Gorev", b =>
                {
                    b.Navigation("Personels");
                });

            modelBuilder.Entity("EkDers.Entity.DbEntity.Izin", b =>
                {
                    b.Navigation("EkDersResults");
                });

            modelBuilder.Entity("EkDers.Entity.DbEntity.IzinTuru", b =>
                {
                    b.Navigation("Izins");
                });
#pragma warning restore 612, 618
        }
    }
}
